version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: boycott-postgres
    restart: always
    environment:
      POSTGRES_DB: boycott_db
      POSTGRES_USER: boycott_user
      POSTGRES_PASSWORD: boycott_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: boycott-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8082:8082"

  frontend:
    build: ./boycott-checker
    environment:
      - REACT_APP_API_URL=http://backend:8082
    ports:
      - "3000:3000"
    depends_on:
      - backend


volumes:
  pgdata:
